# controller_manager_ns: pr2_controller_manager
controller_manager_ns: ""
controller_list:
  - name: katana_arm_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - katana_motor1_pan_joint
      - katana_motor2_lift_joint
      - katana_motor3_lift_joint
      - katana_motor4_lift_joint
      - katana_motor5_wrist_roll_joint

#  - name: r_gripper_controller
#    ns: gripper_action
#    default: true
#    joints:
#      - r_gripper_joint
#      - r_gripper_l_finger_joint
#      - r_gripper_r_finger_joint
#      - r_gripper_l_finger_tip_joint
#      - r_gripper_r_finger_tip_joint
#      - r_gripper_motor_screw_joint
#      - r_gripper_motor_slider_joint
